[project]
name = "aoc-2025"
version = "0.1.0"
description = ""
readme = "../README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "pulp>=3.3.0",
    "pyright>=1.1.407",
    "pytest>=9.0.1",
    "ruff>=0.14.7",
]
